### PR TITLE
Upgrade VuePress, improve jumbotron

### PR DESCRIPTION
**Pull request by ghys**
Image source: https://play.google.com/store/apps/dev?id=7475306295333689578

Signed-off-by: Yannick Schaus <github@schaus.net>

### CODE REVIEW

**Comment by ghys** [comment]
Finally got around to redesigning this jumbotron...
@kaikreuzer please have a look - https://deploy-preview-64--openhabfoundation.netlify.com/ and merge if you agree... I think it's an improvement :)

**Comment by kaikreuzer** [comment]
Hm, I am now missing a bit our corporate "orange" and I actually quite liked the library. I agree though, that the orange header was a bit huge and separating.

**Comment by ghys** [comment]
> I actually quite liked the library

Seriously? :) Matter of taste I guess, but I always found it ugly and out of place. :) It's also a little short in resolution for the parallax imho.
I added a orange filter in front of the image.

**Comment by kaikreuzer** [comment]
>  I always found it ugly

It imho looks very modern and stylish (btw, it's the one in Frankfurt, so it has even a local reference). The houses of the current picture rather look ugly as those are cheap walls, which aren't even straight...

> It's also a little short in resolution for the parallax imho.

The current one in contrast wastes a lot of screen space, not good.

> I added a orange filter in front of the image.

Not convinced, sorry ;-)

**Comment by ghys** [comment]
Ok, I found it in better resolution and replaced.
If you're still not happy after that... I give up.

**Comment by kaikreuzer** [comment]
I am happy, but have small improvement requests 🤣 
Reduce the image size to 2/3 of its height and let the orange shadow end a bit higher already, so that it only covers 80% or so of the image. I bet that'd look even better 😎 .

**Comment by ghys** [comment]
Done.

**Pull request merged**
