### PR TITLE
Small changes on privacy page

### PR DESCRIPTION
**Pull request by MHerbst**

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Hi @MHerbst, very sorry, this PR completely escaped me :-/
May I ask you to rebase it and solve the merge conflict (meanwhile the link has become a real link as it seems)?

Btw, further fixes, improvements & visual enhancements for our website are still very welcome - I am very aware that it looks pretty dull :-/

**Comment by MHerbst** [comment]
Hi @kaikreuzer,

no problem. I was very busy with other things in the last weeks and I also forgot this PR .... Will try to fix it within the next days and I hope to find more time during the next weeks.

> Btw, further fixes, improvements & visual enhancements for our website are still very welcome - I am very aware that it looks pretty dull :-/

I agree with you and I think that all sites in the openHAB "universe" could need some visual enhancements and a more consistent look & feel especially regarding color schemes and fonts. 
But I am more a technician than a designer :-)

**Comment by kaikreuzer** [comment]
> But I am more a technician than a designer :-)

So am I 😥
If you have some good idea what to do about it, let us discuss in the foundation!

**Comment by MHerbst** [comment]
> If you have some good idea what to do about it, let us discuss in the foundation!

Will do it. I wanted to wait until we have a new logo. I think the primary colors on the websites should match the colors used in the logo.

**Comment by MHerbst** [comment]
Rebase did not really solve this problem and it's easier to create a new PR.

**Pull request closed without merging**
